window.winkEnvValues = {
  basePath: '',
  apiEndPoint: '#{apiEndPoint}#',
  environment: '#{environment}#',
  winkLoginRealm: '#{winkLoginRealm}#',
  winkLoginAuthURL: '#{winkLoginAuthURL}#',
  clientIdOfPaymentMerchant: '#{clientIdOfPaymentMerchant}#',
  clientIdOfCheckoutMerchant: '#{clientIdOfCheckoutMerchant}#',
  clientIdOfSubscribeMerchant: '#{clientIdOfSubscribeMerchant}#',
  winkPaymentURL: '#{winkPaymentURL}#',
  testAppURL: '#{testAppURL}#',
  winkPaymentSdkUrl: '#{winkPaymentSdkUrl}#',
  integrityHash: '#{integrityHash}#',
  paymentMerchantAuthKey: '#{paymentMerchantAuthKey}#',
  checkoutMerchantAuthKey: '#{checkoutMerchantAuthKey}#',
  subscribeMerchantAuthKey: '#{subscribeMerchantAuthKey}#',
  paymentId: '491',
  integrationToken: '#{integrationToken}#',
};
